package example;
/* Generated By:JavaCC: Do not edit this line. Calc3iConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Calc3iConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EXP = 9;
  /** RegularExpression Id. */
  int AND = 10;
  /** RegularExpression Id. */
  int OR = 11;
  /** RegularExpression Id. */
  int XOR = 12;
  /** RegularExpression Id. */
  int CONSTANT = 13;
  /** RegularExpression Id. */
  int FLOAT = 14;
  /** RegularExpression Id. */
  int INTEGER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int ID = 17;
  /** RegularExpression Id. */
  int LETTER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "<CONSTANT>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<ID>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
